matrix:
    include:
        - language: python
          python:
              - "2.7"
              - "3.6"
          install: true
          before_script:
              - cd python
          script: pytest

        - language: php
          php:
              - '5.6'
              - '7.0'
          before_script:
              - cd php

        - language: node_js
          node_js:
              - "node"
          before_install:
              - cd javascript
          install:
              - npm install

        - language: lua
          python:
              - "5.4"
          before_install:
              - luarocks install busted
              - cd lua/hello-world
          script:
              - busted

          script: pytest
branches:
    only:
        - master
