matrix:
    include:
        - language: python
          python:
              - "2.7"
              - "3.6"
          install: true
          before_script:
              - cd python
          script: pytest

        - language: php
          php:
              - '5.6'
              - '7.0'
          before_script:
              - cd php

        - language: node_js
          node_js:
              - "iojs"
              - "7"
          before_install:
              - cd javascript
          install:
              - npm install
